package models.genericmodeltouploadedfilerelation.daos

import org.jooq.generated.tables.GenericModelToUploadedFileRelations
import orm.genericmodeltouploadedfilerelationgeneratedrepository.GenericModelToUploadedFileRelationRecord
import models.genericmodeltouploadedfilerelation.GenericModelToUploadedFileRelation

object GenericModelToUploadedFileRelationDestroyDao {



}