package models.genericmodeltouploadedfilerelation.daos

import org.jooq.generated.tables.GenericModelToUploadedFileRelations
import models.genericmodeltouploadedfilerelation.daos.GenericModelToUploadedFileRelationShowDao
import models.genericmodeltouploadedfilerelation.daos.GenericModelToUploadedFileRelationIndexDao
import models.genericmodeltouploadedfilerelation.daos.GenericModelToUploadedFileRelationEditDao
import models.genericmodeltouploadedfilerelation.daos.GenericModelToUploadedFileRelationUpdateDao
import models.genericmodeltouploadedfilerelation.daos.GenericModelToUploadedFileRelationDestroyDao

object GenericModelToUploadedFileRelationDaos {

    val show = GenericModelToUploadedFileRelationShowDao

    val index = GenericModelToUploadedFileRelationIndexDao

    val edit = GenericModelToUploadedFileRelationEditDao

    val update = GenericModelToUploadedFileRelationUpdateDao

    val destroy = GenericModelToUploadedFileRelationDestroyDao

}