package models.contracttouploadeddocumentlink.daos

import org.jooq.generated.tables.ContractToUploadedDocumentLinks
import orm.contracttouploadeddocumentlinkgeneratedrepository.ContractToUploadedDocumentLinkRecord
import models.contracttouploadeddocumentlink.ContractToUploadedDocumentLink

object ContractToUploadedDocumentLinkUpdateDao {



}