package models.contracttouploadeddocumentlink

import models.contracttouploadeddocumentlink.ContractToUploadedDocumentLink
import utils.requestparameters.IParam

class ContractToUploadedDocumentLinkRequestParametersWrapper(val requestParameters: IParam) {



}