package models.userdefinablerelationreason.daos

import org.jooq.generated.tables.UserDefinableRelationReasons
import orm.userdefinablerelationreasongeneratedrepository.UserDefinableRelationReasonRecord
import models.userdefinablerelationreason.UserDefinableRelationReason

object UserDefinableRelationReasonEditDao {



}