package models.documenttemplatecategory.daos

import org.jooq.generated.tables.DocumentTemplateCategories
import orm.documenttemplatecategorygeneratedrepository.DocumentTemplateCategoryRecord
import models.documenttemplatecategory.DocumentTemplateCategory

object DocumentTemplateCategoryDestroyDao {



}