package models.monetaryobligationpart.daos

import org.jooq.generated.tables.MonetaryObligationParts
import orm.monetaryobligationpartgeneratedrepository.MonetaryObligationPartRecord
import models.monetaryobligationpart.MonetaryObligationPart

object MonetaryObligationPartIndexDao {



}