package models.documenttemplatevariable.daos

import org.jooq.generated.tables.DocumentTemplateVariables
import orm.documenttemplatevariablegeneratedrepository.DocumentTemplateVariableRecord
import models.documenttemplatevariable.DocumentTemplateVariable

object DocumentTemplateVariableEditDao {



}