package models.documenttemplatetodocumentvariablelink.daos

import org.jooq.generated.tables.DocumentTemplateToDocumentVariableLinks
import orm.documenttemplatetodocumentvariablelinkgeneratedrepository.DocumentTemplateToDocumentVariableLinkRecord
import models.documenttemplatetodocumentvariablelink.DocumentTemplateToDocumentVariableLink

object DocumentTemplateToDocumentVariableLinkShowDao {



}