package models.approvalsteptoapproverlink.daos

import org.jooq.generated.tables.ApprovalStepToApproverLinks
import orm.approvalsteptoapproverlinkgeneratedrepository.ApprovalStepToApproverLinkRecord
import models.approvalsteptoapproverlink.ApprovalStepToApproverLink

object ApprovalStepToApproverLinkEditDao {



}