package models.jobpositiondelegation.daos

import org.jooq.generated.tables.JobPositionDelegations
import orm.jobpositiondelegationgeneratedrepository.JobPositionDelegationRecord
import models.jobpositiondelegation.JobPositionDelegation

object JobPositionDelegationUpdateDao {



}