package models.approvaltoapproverlink.daos

import org.jooq.generated.tables.ApprovalToApproverLinks
import orm.approvaltoapproverlinkgeneratedrepository.ApprovalToApproverLinkRecord
import models.approvaltoapproverlink.ApprovalToApproverLink

object ApprovalToApproverLinkIndexDao {



}