package models.persontocounterpartylinktouploadeddocumentlink.daos

import org.jooq.generated.tables.PersonToCounterPartyLinkToUploadedDocumentLinks
import orm.persontocounterpartylinktouploadeddocumentlinkgeneratedrepository.PersonToCounterPartyLinkToUploadedDocumentLinkRecord
import models.persontocounterpartylinktouploadeddocumentlink.PersonToCounterPartyLinkToUploadedDocumentLink

object PersonToCounterPartyLinkToUploadedDocumentLinkEditDao {



}