package models.jobpositiontouserlink.daos

import org.jooq.generated.tables.JobPositionToUserLinks
import orm.jobpositiontouserlinkgeneratedrepository.JobPositionToUserLinkRecord
import models.jobpositiontouserlink.JobPositionToUserLink

object JobPositionToUserLinkIndexDao {



}